# Generated by Django 3.2.4 on 2021-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_happy',
            field=models.BooleanField(default=True),
        ),
    ]
